id: P006651
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:12:53.486934
source_metadata:
  id: bdr:W1KG11820
  title: ཡི་དམ་ཁག་གཅིག་གི་བསྐྱེད་རྫོགས་དང་། རྒྱུད་སྡེ་སྤྱི་རྣམ་སོགས།
  author: ''
  volumes:
    1fd30d3e3bfe420e90e92fa7421283bb:
      image_group_id: I1KG11824
      title: ''
      volume_number: 1
      total_pages: 740
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
